import hashlib
import json
import subprocess
from pathlib import Path
from pypdf import PdfReader, PdfWriter, PageObject, Transformation
from PIL import Image
from PIL import ImageDraw, ImageFont
from django.conf import settings
from django.utils import timezone

from .models import BirReceiptCheck
from .models import GmailMailbox
from .stage2 import screenshot_path
from .worker_services import verify_stored_pdf
from workorders.client_directory import archive_final_package, DirectoryUnavailable

def _render_receipt(message, printed_at):
    """Use the local Gmail print-layout renderer, preserving HTML emphasis and lists."""
    renderer = Path(settings.BASE_DIR) / 'receipt_renderer' / 'render.mjs'
    payload = json.dumps({'message': message, 'printedAt': printed_at.isoformat()})
    result = subprocess.run(['node', str(renderer)], input=payload.encode('utf-8'),
                            capture_output=True, check=True)
    return result.stdout


def _footer_pdf(path, text):
    image = Image.new('RGB', (612, 24), 'white')
    draw = ImageDraw.Draw(image)
    try:
        font = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', 8)
    except OSError:
        font = ImageFont.load_default()
    draw.text((10, 7), text, fill=(90, 90, 90), font=font)
    image.save(path, 'PDF', resolution=72.0)

def finalize(check):
    if not check.received_at or check.final_package: return check
    approval=check.approval; order=approval.work_order
    message=check.evidence.get('message',{})
    # Older receipt records predate header capture; use the configured mailbox
    # so their printout still shows the complete Gmail header.
    message = dict(message)
    if not message.get('to'):
        mailbox = GmailMailbox.current()
        message['to'] = mailbox.address if mailbox else settings.GMAIL_ADDRESS
    package_dir=(Path(settings.MEDIA_ROOT)/'final_packages').resolve(); package_dir.mkdir(parents=True,exist_ok=True)
    receipt_name=f'{order.work_order_id}-bir-receipt.pdf'; package_name=f'{order.work_order_id}-final-package.pdf'
    receipt_path=package_dir/receipt_name; receipt_path.write_bytes(_render_receipt(message, check.received_at))
    writer=PdfWriter()
    screenshot=screenshot_path(approval); screenshot_pdf=package_dir/f'{order.work_order_id}-submission-screenshot.pdf'
    # Keep the evidence page Legal too, scaling the captured screen to fit
    # inside the same sheet used by the filed return and receipt.
    with Image.open(screenshot) as image:
        image.convert('RGB').save(screenshot_pdf, 'PDF', resolution=150.0)
    source = PdfReader(str(screenshot_pdf)).pages[0]
    legal = PageObject.create_blank_page(width=612, height=1008)
    scale = min(612 / float(source.mediabox.width), 1008 / float(source.mediabox.height))
    x = (612 - float(source.mediabox.width) * scale) / 2
    y = (1008 - float(source.mediabox.height) * scale) / 2
    legal.merge_transformed_page(source, Transformation().scale(scale).translate(x, y))
    normalized = PdfWriter(); normalized.add_page(legal)
    with screenshot_pdf.open('wb') as output: normalized.write(output)
    for source in [verify_stored_pdf(order), receipt_path, screenshot_pdf]:
        reader=PdfReader(str(source)); [writer.add_page(page) for page in reader.pages]
    creator = order.created_by.get_full_name() or order.created_by.get_username()
    footer_pdf = package_dir / f'{order.work_order_id}-footer.pdf'
    _footer_pdf(footer_pdf, f'Generated by {creator} | eBIR full filing package')
    footer = PdfReader(str(footer_pdf)).pages[0]
    for page in writer.pages:
        page.merge_translated_page(footer, 0, 0, expand=False)
    package_path=package_dir/package_name; temporary=package_path.with_suffix('.part.pdf')
    with temporary.open('wb') as output: writer.write(output)
    footer_pdf.unlink(missing_ok=True)
    temporary.replace(package_path)
    digest=hashlib.sha256(package_path.read_bytes()).hexdigest()
    archive = {'status': 'not_configured'}
    try:
        archive = archive_final_package(order.client, order, order.review_pdf_filename, package_path.read_bytes())
        if archive.get('status') == 'saved':
            archive['saved_at'] = timezone.now().isoformat()
    except DirectoryUnavailable as exc:
        archive = {'status': 'failed', 'error': str(exc)}
    check.confirmation_pdf=f'final_packages/{receipt_name}'; check.final_package=f'final_packages/{package_name}'
    evidence = dict(check.evidence or {})
    evidence['client_archive'] = archive
    check.evidence = evidence
    check.final_package_sha256=digest; check.finalized_at=timezone.now(); check.save(update_fields=['confirmation_pdf','final_package','final_package_sha256','finalized_at','evidence'])
    approval.state='BIR_RECEIPT_CONFIRMED'; approval.save(_service_write=True)
    return check
