"""Conservative Stage 1 prototype policy; not an automatic retry scheduler."""
from datetime import timedelta

LEASE_DURATION = timedelta(minutes=30)
MAX_PDF_BYTES = 25 * 1024 * 1024
POLL_SECONDS = 15
VM_WORKING_ROOT = r'C:\TaxAutomation\Working'
VM_XML_ROOT = r'C:\eBIRForms\savefile'
FAILURE_STATUSES = frozenset({'PREPARATION_FAILED_PDF_NOT_FOUND','PREPARATION_FAILED_XML_NOT_FOUND','PROFILE_REVIEW_REQUIRED','FAILED_SYSTEM','FAILED_BUSINESS'})
ENABLED_STATUSES = FAILURE_STATUSES | {'DRAFT','READY_TO_PREPARE','PROCESSING_PREPARATION','AWAITING_SUBMISSION_APPROVAL'}
