# Generated by Django 5.2.17 on 2026-09-14 08:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_api', '0001_initial'),
        ('workorders', '0005_remove_workorder_wo_m2_enabled_statuses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationAttempt',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('lease_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('lease_expires_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned after operator review')], default='RUNNING', max_length=12)),
                ('execution_slot', models.PositiveSmallIntegerField(blank=True, default=1, null=True, unique=True)),
                ('result_digest', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_attempts', to='automation_api.agent')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorders.workordersnapshot')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_attempts', to='workorders.workorder')),
            ],
            options={
                'ordering': ('started_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('execution_slot', 1), ('state', 'RUNNING')), models.Q(('completed_at__isnull', False), ('execution_slot__isnull', True), ('state__in', ['SUCCEEDED', 'FAILED', 'ABANDONED'])), _connector='OR'), name='attempt_valid_state_slot'), models.UniqueConstraint(condition=models.Q(('state', 'RUNNING')), fields=('work_order',), name='one_active_attempt_per_order')],
            },
        ),
    ]
