# Generated by Django 5.2.17 on 2026-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_api', '0002_preparationattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
