# Generated by Django 5.2.17 on 2026-09-15 08:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_api', '0003_agent_last_seen_at'),
        ('workorders', '0010_alter_client_email_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage2Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('comment', models.TextField(blank=True)),
                ('state', models.CharField(default='QUEUED', max_length=40)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage2_approval', to='automation_api.preparationattempt')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workorders.workordersnapshot')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stage2_approval', to='workorders.workorder')),
            ],
            options={
                'permissions': [('approve_stage2', 'Can approve Stage 2 revalidation')],
            },
        ),
    ]
