# Generated by Django 5.2.17 on 2026-09-17 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_api', '0005_stage2_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage2approval',
            name='submission_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2approval',
            name='success_screenshot',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='stage2approval',
            name='success_screenshot_sha256',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')]),
        ),
    ]
