# Generated by Django 5.2.17 on 2026-09-21 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_api', '0006_stage2approval_submission_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirReceiptCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('submitted_after', models.DateTimeField()),
                ('next_check_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=250)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_check', to='automation_api.stage2approval')),
            ],
        ),
    ]
