# Generated by Django 5.2.17 on 2026-09-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_api', '0009_birreceiptcheck_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='birreceiptcheck',
            name='trrc_escalation_error',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='birreceiptcheck',
            name='trrc_escalation_recipient',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='birreceiptcheck',
            name='trrc_escalation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
