# Generated by Django 5.2.17 on 2026-10-06 08:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_api', '0010_birreceiptcheck_trrc_escalation_error_and_more'),
        ('workorders', '0023_cancelled_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationCleanup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archive_path', models.CharField(blank=True, max_length=1000)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation_api.agent')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation_api.preparationattempt')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_cleanup', to='workorders.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
