# Generated by Django 5.2.17 on 2026-10-07 03:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_api', '0012_prepared_return_archive'),
        ('workorders', '0023_cancelled_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionScreenshotArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('RETRY', 'RETRY'), ('SAVED', 'SAVED'), ('BLOCKED', 'BLOCKED')], default='PENDING', max_length=12)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=1000)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission_screenshot_archive', to='workorders.workorder')),
            ],
        ),
    ]
