# Generated by Django 5.2.17 on 2026-10-01 06:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('thread_key', models.CharField(db_index=True, max_length=100)),
                ('chat_id', models.CharField(max_length=100)),
                ('chat_type', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('sender_open_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField(max_length=20000)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature request'), ('change', 'Change to existing behaviour'), ('data', 'Data issue'), ('question', 'Unanswered question'), ('other', 'Other')], max_length=20)),
                ('summary', models.CharField(max_length=200)),
                ('details', models.TextField(max_length=8000)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('done', 'Done'), ('declined', 'Declined')], db_index=True, default='new', max_length=20)),
                ('reporter_open_id', models.CharField(blank=True, max_length=150)),
                ('reporter_name', models.CharField(blank=True, max_length=150)),
                ('chat_id', models.CharField(blank=True, max_length=100)),
                ('source_message_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
