# Generated by Django 5.2.17 on 2026-10-05 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feishu_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(max_length=36, unique=True)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('announced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
