# Generated by Django 5.2.17 on 2026-10-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feishu_bot', '0002_approval_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalalert',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='approvalalert',
            name='message_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
