# Generated by Django 5.2.17 on 2026-10-05 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feishu_bot', '0003_approval_alert_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('online', models.BooleanField(default=True)),
                ('connection', models.CharField(blank=True, max_length=100)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
