"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Environment variables override the ignored local .env file.
load_dotenv(BASE_DIR / ".env", override=False)
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if len(SECRET_KEY) < 50 or SECRET_KEY == "replace-with-a-secure-random-secret":
    raise ImproperlyConfigured("Set a random DJANGO_SECRET_KEY of at least 50 characters.")

_debug_value = os.environ.get("DJANGO_DEBUG", "False").lower()
if _debug_value not in {"true", "false"}:
    raise ImproperlyConfigured("DJANGO_DEBUG must be True or False.")
DEBUG = _debug_value == "true"
ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost"
    ).split(",") if host.strip()
]
if not ALLOWED_HOSTS or any(host not in {"127.0.0.1", "localhost"} for host in ALLOWED_HOSTS):
    raise ImproperlyConfigured("Milestone 1 only permits loopback hosts.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'workorders.apps.WorkordersConfig',
    'automation_api.apps.AutomationApiConfig',
    'audit.apps.AuditConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Private storage only. Never add static(settings.MEDIA_URL, ...) to urls.py.
# Future PDF views must authorize each request before opening stored files.
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = ''

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
CLIENT_FILES_URL = os.environ.get('CLIENT_FILES_URL', '').rstrip('/')
COR_NODE_MODULES = os.environ.get('COR_NODE_MODULES', '')
# Separate ignored file keeps the gateway key out of templates and browser code.
from dotenv import dotenv_values
_gds = dotenv_values(BASE_DIR / 'secrets' / 'gds-gateway.env')
GDS_BASE_URL = os.environ.get('GDS_BASE_URL', _gds.get('GDS_BASE_URL', '') or '').rstrip('/')
GDS_API_KEY = os.environ.get('GDS_API_KEY', _gds.get('GDS_API_KEY', '') or '')
GDS_MODEL = os.environ.get('GDS_MODEL', _gds.get('GDS_MODEL', '') or '')
LOGIN_REDIRECT_URL = 'workorders:clients'
LOGOUT_REDIRECT_URL = 'login'
