"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Environment variables override the ignored local .env file.
load_dotenv(BASE_DIR / ".env", override=False)
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if len(SECRET_KEY) < 50 or SECRET_KEY == "replace-with-a-secure-random-secret":
    raise ImproperlyConfigured("Set a random DJANGO_SECRET_KEY of at least 50 characters.")

_debug_value = os.environ.get("DJANGO_DEBUG", "False").lower()
if _debug_value not in {"true", "false"}:
    raise ImproperlyConfigured("DJANGO_DEBUG must be True or False.")
DEBUG = _debug_value == "true"
ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost"
    ).split(",") if host.strip()
]
if not ALLOWED_HOSTS or any(host not in {"127.0.0.1", "localhost"} for host in ALLOWED_HOSTS):
    raise ImproperlyConfigured("Milestone 1 only permits loopback hosts.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'workorders.apps.WorkordersConfig',
    'automation_api.apps.AutomationApiConfig',
    'audit.apps.AuditConfig',
    'feishu_bot.apps.FeishuBotConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'audit.middleware.OperationalLoggingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Private storage only. Never add static(settings.MEDIA_URL, ...) to urls.py.
# Future PDF views must authorize each request before opening stored files.
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = ''

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
CLIENT_FILES_URL = os.environ.get('CLIENT_FILES_URL', 'http://127.0.0.1:3020').rstrip('/')
COR_NODE_MODULES = os.environ.get('COR_NODE_MODULES', '')
# Separate ignored file keeps the gateway key out of templates and browser code.
from dotenv import dotenv_values
_gds = dotenv_values(BASE_DIR / 'secrets' / 'gds-gateway.env')
GDS_BASE_URL = os.environ.get('GDS_BASE_URL', _gds.get('GDS_BASE_URL', '') or '').rstrip('/')
GDS_API_KEY = os.environ.get('GDS_API_KEY', _gds.get('GDS_API_KEY', '') or '')
GDS_MODEL = os.environ.get('GDS_MODEL', _gds.get('GDS_MODEL', '') or '')
LOGIN_REDIRECT_URL = 'workorders:clients'
LOGOUT_REDIRECT_URL = 'login'

# Enable only after the VM parent routes and live-dialog selectors are reviewed.
ENABLE_0619F_SUBMISSION = os.environ.get('ENABLE_0619F_SUBMISSION', '0') == '1'
ENABLE_1601EQ_SUBMISSION = os.environ.get('ENABLE_1601EQ_SUBMISSION', '0') == '1'
ENABLE_1601C_SUBMISSION = os.environ.get('ENABLE_1601C_SUBMISSION', '0') == '1'

GMAIL_CLIENT_ID = os.environ.get('GMAIL_CLIENT_ID', '')
GMAIL_CLIENT_SECRET = os.environ.get('GMAIL_CLIENT_SECRET', '')
GMAIL_REDIRECT_URI = os.environ.get('GMAIL_REDIRECT_URI', 'http://127.0.0.1:8000/settings/gmail/callback/')
GMAIL_TOKEN_FILE = os.environ.get('GMAIL_TOKEN_FILE', str(BASE_DIR / 'secrets' / 'gmail-token.json'))
GMAIL_REFRESH_TOKEN = os.environ.get('GMAIL_REFRESH_TOKEN', os.environ.get('GOOGLE_REFRESH_TOKEN', ''))
GMAIL_ADDRESS = os.environ.get('GMAIL_ADDRESS', '')
GMAIL_APP_PASSWORD = os.environ.get('GMAIL_APP_PASSWORD', '').replace(' ', '')
GMAIL_RECEIPT_SENDER = os.environ.get('GMAIL_RECEIPT_SENDER', 'ebirforms-noreply@bir.gov.ph').strip().lower()
TRRC_ESCALATION_RECIPIENT = os.environ.get('TRRC_ESCALATION_RECIPIENT', 'heiner@gds.ph').strip().lower()
TRRC_ESCALATION_AFTER_DAYS = int(os.environ.get('TRRC_ESCALATION_AFTER_DAYS', '7'))
TRRC_ESCALATION_AFTER_MINUTES = int(os.environ.get('TRRC_ESCALATION_AFTER_MINUTES', '0'))
FEISHU_APP_ID = os.environ.get('FEISHU_APP_ID', '')
FEISHU_APP_SECRET = os.environ.get('FEISHU_APP_SECRET', '')
FEISHU_TENANT_KEY = os.environ.get('FEISHU_TENANT_KEY', '')
FEISHU_REDIRECT_URI = os.environ.get('FEISHU_REDIRECT_URI', '')

# Feishu assistant bot (feishu_bot). Defaults to the sign-in app: open IDs are per app,
# so only the same app can map a chat sender to their dashboard account.
FEISHU_BOT_APP_ID = os.environ.get('FEISHU_BOT_APP_ID', FEISHU_APP_ID)
FEISHU_BOT_APP_SECRET = os.environ.get('FEISHU_BOT_APP_SECRET', FEISHU_APP_SECRET)
FEISHU_BOT_TENANT_KEY = os.environ.get('FEISHU_BOT_TENANT_KEY', FEISHU_TENANT_KEY)
FEISHU_BOT_SITE_URL = os.environ.get('FEISHU_BOT_SITE_URL', os.environ.get('EBIR_SITE', 'http://127.0.0.1:8000')).rstrip('/')
FEISHU_BOT_DEVELOPER_NAME = os.environ.get('FEISHU_BOT_DEVELOPER_NAME', 'the developer')
FEISHU_BOT_FEEDBACK_CHAT_ID = os.environ.get('FEISHU_BOT_FEEDBACK_CHAT_ID', '')
FEISHU_BOT_GROUP_DATA = os.environ.get('FEISHU_BOT_GROUP_DATA', 'False').lower() == 'true'
FEISHU_BOT_HOURLY_LIMIT = int(os.environ.get('FEISHU_BOT_HOURLY_LIMIT', '40'))
FEISHU_BOT_MODEL = os.environ.get('FEISHU_BOT_MODEL', 'claude-opus-5-5')
# 'api' uses ANTHROPIC_API_KEY; 'claude-cli' runs the locally signed-in Claude Code CLI (docs-only).
FEISHU_BOT_BACKEND = os.environ.get('FEISHU_BOT_BACKEND', 'api' if os.environ.get('ANTHROPIC_API_KEY') else 'claude-cli')
FEISHU_BOT_CLAUDE_CLI = os.environ.get('FEISHU_BOT_CLAUDE_CLI', 'claude')
FEISHU_BOT_CLI_TIMEOUT = int(os.environ.get('FEISHU_BOT_CLI_TIMEOUT', '240'))
# Claude CLI backend: a view-only dashboard account the bot signs in with to screenshot FEISHU_BOT_SITE_URL.
FEISHU_BOT_DASHBOARD_USERNAME = os.environ.get('FEISHU_BOT_DASHBOARD_USERNAME', '')
FEISHU_BOT_DASHBOARD_PASSWORD = os.environ.get('FEISHU_BOT_DASHBOARD_PASSWORD', '')
# Alert a Feishu chat when a live work order starts awaiting submission approval (empty chat id: off).
FEISHU_BOT_APPROVAL_CHAT_ID = os.environ.get('FEISHU_BOT_APPROVAL_CHAT_ID', '')
FEISHU_BOT_APPROVAL_POLL_SECONDS = max(30, int(os.environ.get('FEISHU_BOT_APPROVAL_POLL_SECONDS', '120')))
# Clients whose name matches this (case-insensitive regex) are never announced; default skips test clients.
FEISHU_BOT_APPROVAL_SKIP_CLIENTS = os.environ.get('FEISHU_BOT_APPROVAL_SKIP_CLIENTS', r'\btest\b')
# Feishu open_ids (comma-separated) messaged privately when a live automation worker goes offline or comes back.
FEISHU_BOT_WORKER_ALERT_TO = [x.strip() for x in os.environ.get('FEISHU_BOT_WORKER_ALERT_TO', '').split(',') if x.strip()]
# Approval and package alerts @mention (ping) the creator; False shows the name in bold without a ping.
FEISHU_BOT_ALERT_MENTIONS = os.environ.get('FEISHU_BOT_ALERT_MENTIONS', 'True').lower() == 'true'
# Dashboard "Created by" name to Feishu open_id, for real @mentions: "CHRIS JOHN INDOC=ou_x; OTHER NAME=ou_y".
FEISHU_BOT_APPROVAL_MENTIONS = os.environ.get('FEISHU_BOT_APPROVAL_MENTIONS', '')

ENABLE_1600VT_SUBMISSION = os.environ.get('ENABLE_1600VT_SUBMISSION', '0') == '1'
