# Generated by Django 5.2.17 on 2026-09-14 06:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation_api', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('STATUS_CHANGED', 'Status changed'), ('PREPARATION_RESULT', 'Preparation result (reserved)'), ('APPROVED', 'Approved (reserved)'), ('REJECTED', 'Rejected (reserved)'), ('API_LEASE', 'API lease (reserved)'), ('AGENT_CREATED', 'Agent created'), ('AGENT_TOKEN_ROTATED', 'Agent token rotated'), ('AGENT_DISABLED', 'Agent disabled')], max_length=30)),
                ('old_status', models.CharField(blank=True, max_length=40)),
                ('new_status', models.CharField(blank=True, max_length=40)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ebir_audit_events', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='automation_api.agent')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='workorders.workorder')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', True), ('work_order__isnull', False)), models.Q(('agent__isnull', False), ('work_order__isnull', True)), _connector='OR'), name='audit_exactly_one_subject')],
            },
        ),
    ]
