# Generated by Django 5.2.17 on 2026-09-14 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('automation_api', '0001_initial'),
        ('workorders', '0002_client_clientfilingprofile_formdefinition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditevent',
            name='audit_exactly_one_subject',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='workorders.client'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='client_filing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='workorders.clientfilingprofile'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='form_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='workorders.formdefinition'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='workorders.workordersnapshot'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='kind',
            field=models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('STATUS_CHANGED', 'Status changed'), ('PREPARATION_RESULT', 'Preparation result (reserved)'), ('APPROVED', 'Approved (reserved)'), ('REJECTED', 'Rejected (reserved)'), ('API_LEASE', 'API lease (reserved)'), ('AGENT_CREATED', 'Agent created'), ('AGENT_TOKEN_ROTATED', 'Agent token rotated'), ('AGENT_DISABLED', 'Agent disabled'), ('CONFIG_CREATED', 'Configuration created'), ('CONFIG_EDITED', 'Configuration edited'), ('SNAPSHOT_REFRESHED', 'Snapshot refreshed'), ('LEGACY_LINKED', 'Historical work order linked')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', True), ('client__isnull', True), ('client_filing_profile__isnull', True), ('form_definition__isnull', True), ('work_order__isnull', False)), models.Q(('agent__isnull', False), ('client__isnull', True), ('client_filing_profile__isnull', True), ('form_definition__isnull', True), ('work_order__isnull', True)), models.Q(('agent__isnull', True), ('client__isnull', False), ('client_filing_profile__isnull', True), ('form_definition__isnull', True), ('work_order__isnull', True)), models.Q(('agent__isnull', True), ('client__isnull', True), ('client_filing_profile__isnull', True), ('form_definition__isnull', False), ('work_order__isnull', True)), models.Q(('agent__isnull', True), ('client__isnull', True), ('client_filing_profile__isnull', False), ('form_definition__isnull', True), ('work_order__isnull', True)), _connector='OR'), name='audit_exactly_one_subject'),
        ),
    ]
