# Generated by Django 5.2.17 on 2026-09-14 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_auditevent_audit_exactly_one_subject_and_more'),
        ('automation_api', '0002_preparationattempt'),
        ('workorders', '0005_remove_workorder_wo_m2_enabled_statuses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='performed_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_events', to='automation_api.agent'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ebir_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='kind',
            field=models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('STATUS_CHANGED', 'Status changed'), ('PREPARATION_RESULT', 'Preparation result'), ('APPROVED', 'Approved (reserved)'), ('REJECTED', 'Rejected (reserved)'), ('API_LEASE', 'Preparation lease'), ('AGENT_CREATED', 'Agent created'), ('AGENT_TOKEN_ROTATED', 'Agent token rotated'), ('AGENT_DISABLED', 'Agent disabled'), ('PDF_UPLOADED', 'Prepared PDF uploaded'), ('LEASE_RENEWED', 'Preparation lease renewed'), ('ATTEMPT_ABANDONED', 'Preparation stopped by operator'), ('CONFIG_CREATED', 'Configuration created'), ('CONFIG_EDITED', 'Configuration edited'), ('SNAPSHOT_REFRESHED', 'Snapshot refreshed'), ('LEGACY_LINKED', 'Historical work order linked')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('performed_by_agent__isnull', True)), models.Q(('actor__isnull', True), ('performed_by_agent__isnull', False)), _connector='OR'), name='audit_exactly_one_actor'),
        ),
    ]
