# Generated by Django 5.2.17 on 2026-09-14 06:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
import workorders.models
import workorders.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_id', models.CharField(editable=False, max_length=48, unique=True)),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('client_name_safe', models.CharField(editable=False, max_length=110)),
                ('tin1', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[0-9]{3}\\Z', 'Enter exactly three numeric digits.')])),
                ('tin2', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[0-9]{3}\\Z', 'Enter exactly three numeric digits.')])),
                ('tin3', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[0-9]{3}\\Z', 'Enter exactly three numeric digits.')])),
                ('tin4', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('\\A[0-9]{5}\\Z', 'Enter exactly five numeric branch digits.')])),
                ('rdo_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[0-9A-Z]{3}\\Z', 'Enter three uppercase letters or digits, such as 047 or 53A.')])),
                ('registered_name', models.CharField(max_length=200)),
                ('registered_address', models.TextField(max_length=2000)),
                ('zip_code', models.CharField(max_length=20)),
                ('telephone_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('line_of_business', models.CharField(max_length=200)),
                ('form_code', models.CharField(default='2551Q', max_length=20)),
                ('form_selection_text', models.CharField(default='BIR Form 2551Qv2018', max_length=80)),
                ('expected_form_number', models.CharField(default='2551Qv2018', max_length=30)),
                ('filing_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('\\A[0-9]{4}\\Z', 'Enter a four-digit filing year.')])),
                ('filing_quarter', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('year_end_month', models.CharField(default='12', max_length=2)),
                ('calendar_year', models.BooleanField(default=True)),
                ('atc_code', models.CharField(max_length=6, validators=[workorders.validators.validate_atc_2551qv2018])),
                ('zero_filing_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_PREPARE', 'Ready to prepare'), ('PROCESSING_PREPARATION', 'Processing preparation'), ('AWAITING_SUBMISSION_APPROVAL', 'Awaiting submission approval'), ('PREPARATION_FAILED_PDF_NOT_FOUND', 'Preparation failed: PDF not found'), ('PREPARATION_FAILED_XML_NOT_FOUND', 'Preparation failed: XML not found'), ('PROFILE_REVIEW_REQUIRED', 'Profile review required'), ('APPROVED_FOR_SUBMISSION', 'Approved for submission'), ('REJECTED', 'Rejected'), ('PROCESSING_SUBMISSION', 'Processing submission'), ('BLOCKED_NOT_APPROVED', 'Blocked: not approved'), ('WORK_ORDER_VERIFICATION_FAILED', 'Work-order verification failed'), ('SAVED_RETURN_NOT_UNIQUE', 'Saved return not unique'), ('SAVED_RETURN_ROW_NOT_FOUND', 'Saved return row not found'), ('APPROVED_READY_TO_SUBMIT', 'Approved and ready to submit (submission disabled)'), ('SUBMITTING', 'Submitting (reserved)'), ('SUBMITTED', 'Submitted (reserved)'), ('WAITING_FOR_BIR_CONFIRMATION', 'Waiting for BIR confirmation (reserved)'), ('COMPLETED', 'Completed (reserved)'), ('FAILED_SYSTEM', 'System failure'), ('FAILED_BUSINESS', 'Business failure')], db_index=True, default='DRAFT', editable=False, max_length=40)),
                ('prepared_pdf', models.FileField(blank=True, editable=False, max_length=300, upload_to=workorders.models.prepared_pdf_upload_path)),
                ('prepared_pdf_sha256', models.CharField(blank=True, editable=False, max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('saved_xml_path', models.CharField(blank=True, editable=False, help_text='Automation-VM-local metadata, never opened by Django.', max_length=500)),
                ('page1_path', models.CharField(blank=True, editable=False, max_length=500)),
                ('page2_path', models.CharField(blank=True, editable=False, max_length=500)),
                ('preparation_status_output', models.CharField(blank=True, editable=False, max_length=40)),
                ('submission_status', models.CharField(blank=True, editable=False, max_length=40)),
                ('error_code', models.CharField(blank=True, editable=False, max_length=100)),
                ('error_message', models.TextField(blank=True, editable=False)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('leased_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('agent_name', models.CharField(blank=True, editable=False, max_length=100)),
                ('attempt_count', models.PositiveIntegerField(default=0, editable=False)),
                ('approved_for_submission', models.BooleanField(default=False, editable=False)),
                ('approval_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('approval_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approval_comment', models.TextField(blank=True, editable=False)),
                ('approved_pdf_sha256', models.CharField(blank=True, editable=False, max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_work_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('filing_quarter__gte', 1), ('filing_quarter__lte', 4)), name='wo_valid_quarter'), models.CheckConstraint(condition=models.Q(('calendar_year', True), ('expected_form_number', '2551Qv2018'), ('form_code', '2551Q'), ('form_selection_text', 'BIR Form 2551Qv2018'), ('year_end_month', '12')), name='wo_current_form_scope'), models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'READY_TO_PREPARE'])), name='wo_m2_enabled_statuses'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'READY_TO_PREPARE'), _negated=True), ('zero_filing_approved', True), _connector='OR'), name='wo_ready_requires_zero_confirmation'), models.CheckConstraint(condition=models.Q(('approved_for_submission', False)), name='wo_m2_no_submission_approval'), models.CheckConstraint(condition=models.Q(('atc_code', ''), _negated=True), name='wo_atc_required'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='wo_positive_version')],
            },
        ),
    ]
