# Generated by Django 5.2.17 on 2026-09-14 07:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=80, unique=True)),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('NON_INDIVIDUAL', 'Non-individual')], max_length=20)),
                ('registered_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('tin1', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[0-9]{3}\\Z', 'Enter exactly three numeric digits.')])),
                ('tin2', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[0-9]{3}\\Z', 'Enter exactly three numeric digits.')])),
                ('tin3', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[0-9]{3}\\Z', 'Enter exactly three numeric digits.')])),
                ('tin4', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('\\A[0-9]{5}\\Z', 'Enter exactly five numeric branch digits.')])),
                ('rdo_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[0-9A-Z]{3}\\Z', 'Enter three uppercase letters or digits, such as 047 or 53A.')])),
                ('registered_address', models.TextField(max_length=2000)),
                ('zip_code', models.CharField(max_length=20)),
                ('telephone_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('line_of_business', models.CharField(max_length=200)),
                ('client_folder_path', models.CharField(blank=True, help_text='Automation-VM-local metadata only; Django never opens this path.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('registered_name', 'client_code'),
            },
        ),
        migrations.CreateModel(
            name='ClientFilingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('year_end_month', models.CharField(default='12', max_length=2, validators=[django.core.validators.RegexValidator('\\A(?:0[1-9]|1[0-2])\\Z', 'Enter a two-digit month from 01 to 12.')])),
                ('calendar_or_fiscal', models.CharField(choices=[('CALENDAR', 'Calendar'), ('FISCAL', 'Fiscal')], default='CALENDAR', max_length=8)),
                ('default_atc_code', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('default_form_data', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('client__registered_name', 'form_definition__form_code'),
            },
        ),
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_code', models.CharField(max_length=20)),
                ('form_version', models.CharField(blank=True, max_length=30)),
                ('expected_form_number', models.CharField(blank=True, max_length=30)),
                ('display_name', models.CharField(max_length=200)),
                ('form_selection_text', models.CharField(blank=True, max_length=100)),
                ('filing_frequency', models.CharField(choices=[('QUARTERLY', 'Quarterly'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=12)),
                ('automation_key', models.CharField(blank=True, max_length=100)),
                ('preparation_automation_available', models.BooleanField(default=False)),
                ('submission_automation_available', models.BooleanField(default=False, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('definition_key', models.CharField(max_length=100, unique=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('form_code', 'form_version'),
            },
        ),
        migrations.CreateModel(
            name='WorkOrderSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('source_versions', models.JSONField(blank=True, default=dict)),
                ('sha256', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('work_order', 'revision'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='workorder',
            name='wo_valid_quarter',
        ),
        migrations.RemoveConstraint(
            model_name='workorder',
            name='wo_current_form_scope',
        ),
        migrations.RemoveConstraint(
            model_name='workorder',
            name='wo_atc_required',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='client_id',
            new_name='legacy_client_reference',
        ),
        migrations.AddField(
            model_name='workorder',
            name='filing_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='legacy_client_reference',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='zero_filing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='atc_code',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='calendar_year',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='client_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='client_name_safe',
            field=models.CharField(blank=True, editable=False, max_length=110),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='email_address',
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='expected_form_number',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='filing_quarter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='form_code',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='form_selection_text',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='line_of_business',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='rdo_code',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='registered_address',
            field=models.TextField(blank=True, editable=False, max_length=2000),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='registered_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='telephone_number',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tin1',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tin2',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tin3',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tin4',
            field=models.CharField(blank=True, editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='year_end_month',
            field=models.CharField(blank=True, editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='zip_code',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('client_type__in', ['INDIVIDUAL', 'NON_INDIVIDUAL'])), name='client_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='client_positive_version'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='client',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='workorders.client'),
        ),
        migrations.AddField(
            model_name='clientfilingprofile',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filing_profiles', to='workorders.client'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='client_filing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='workorders.clientfilingprofile'),
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.UniqueConstraint(fields=('form_code', 'form_version'), name='form_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('submission_automation_available', False)), name='form_submission_disabled'),
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='form_positive_version'),
        ),
        migrations.AddField(
            model_name='clientfilingprofile',
            name='form_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_profiles', to='workorders.formdefinition'),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='workorders.workorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='current_snapshot',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_orders', to='workorders.workordersnapshot'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('filing_quarter__isnull', True), models.Q(('filing_quarter__gte', 1), ('filing_quarter__lte', 4)), _connector='OR'), name='wo_valid_quarter'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('filing_month__isnull', True), models.Q(('filing_month__gte', 1), ('filing_month__lte', 12)), _connector='OR'), name='wo_valid_month'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('filing_month__isnull', True), ('filing_quarter__isnull', True), _connector='OR'), name='wo_one_period_granularity'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', True), ('client_filing_profile__isnull', True)), models.Q(('client__isnull', False), ('client_filing_profile__isnull', False)), _connector='OR'), name='wo_client_profile_pair'),
        ),
        migrations.AddConstraint(
            model_name='clientfilingprofile',
            constraint=models.UniqueConstraint(fields=('client', 'form_definition'), name='unique_client_form_profile'),
        ),
        migrations.AddConstraint(
            model_name='clientfilingprofile',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='profile_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='workordersnapshot',
            constraint=models.UniqueConstraint(fields=('work_order', 'revision'), name='snapshot_unique_revision'),
        ),
        migrations.AddConstraint(
            model_name='workordersnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='snapshot_positive_revision'),
        ),
    ]
