# Generated by Django 5.2.17 on 2026-09-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_seed_definitions_preserve_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='creation_request_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
