# Generated by Django 5.2.17 on 2026-09-14 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_workorder_creation_request_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workorder',
            name='wo_m2_enabled_statuses',
        ),
        migrations.AddField(
            model_name='workorder',
            name='prepared_pdf_vm_path',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'AWAITING_SUBMISSION_APPROVAL'), _negated=True), models.Q(models.Q(('prepared_pdf', ''), _negated=True), models.Q(('prepared_pdf_sha256', ''), _negated=True), models.Q(('saved_xml_path', ''), _negated=True), models.Q(('prepared_pdf_vm_path', ''), _negated=True)), _connector='OR'), name='wo_review_requires_pdf_xml'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'READY_TO_PREPARE', 'PROCESSING_PREPARATION', 'AWAITING_SUBMISSION_APPROVAL', 'PREPARATION_FAILED_PDF_NOT_FOUND', 'PREPARATION_FAILED_XML_NOT_FOUND', 'PROFILE_REVIEW_REQUIRED', 'FAILED_SYSTEM', 'FAILED_BUSINESS'])), name='wo_m2_enabled_statuses'),
        ),
    ]
