# Generated by Django 5.2.17 on 2026-09-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_remove_workorder_wo_m2_enabled_statuses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at', 'id'], 'permissions': [('view_prepared_pdf', 'Can download protected prepared PDF')]},
        ),
    ]
