# Generated by Django 5.2.17 on 2026-09-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_alter_workorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
