# Generated by Django 5.2.17 on 2026-09-15 03:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_workorder_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=255, unique=True)),
                ('source_path', models.CharField(max_length=2000)),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_text', models.TextField()),
                ('reviewed_forms', models.JSONField(default=list)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registration_setup', to='workorders.client')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
