# Generated by Django 5.2.17 on 2026-09-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0009_cor_form_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
