# Generated by Django 5.2.17 on 2026-09-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0010_alter_client_email_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCardScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('documents', models.JSONField(default=list)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
