# Generated by Django 5.2.17 on 2026-09-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0011_registrationcardscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcardscan',
            name='preferred_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='registrationcardscan',
            name='selection_note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
