# Generated by Django 5.2.17 on 2026-09-22 05:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0013_form_1601c'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='workorders.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('user', 'client'), name='saved_unique_client'), models.UniqueConstraint(condition=models.Q(('folder', ''), _negated=True), fields=('user', 'folder'), name='saved_unique_folder'), models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', False), ('folder', '')), models.Q(('client__isnull', True), models.Q(('folder', ''), _negated=True)), _connector='OR'), name='saved_exactly_one_target')],
            },
        ),
    ]
