# Generated by Django 5.2.17 on 2026-09-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0017_tasknoticeread'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rdo_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='RDO email'),
        ),
    ]
