# Generated by Django 5.2.17 on 2026-09-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0018_client_rdo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rdo_email',
            field=models.EmailField(blank=True, default='contact_us@bir.gov.ph', max_length=254, verbose_name='RDO email'),
        ),
    ]
