# Generated by Django 5.2.17 on 2026-10-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0021_form_1600vt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('DRAFT', 'Draft'), ('READY_TO_PREPARE', 'Ready to prepare'), ('PROCESSING_PREPARATION', 'Processing preparation'), ('AWAITING_SUBMISSION_APPROVAL', 'Awaiting submission approval'), ('PREPARATION_FAILED_PDF_NOT_FOUND', 'Preparation failed: PDF not found'), ('PREPARATION_FAILED_XML_NOT_FOUND', 'Preparation failed: XML not found'), ('PROFILE_REVIEW_REQUIRED', 'Profile review required'), ('APPROVED_FOR_SUBMISSION', 'Approved for submission'), ('REJECTED', 'Rejected'), ('PROCESSING_SUBMISSION', 'Processing submission'), ('BLOCKED_NOT_APPROVED', 'Blocked: not approved'), ('WORK_ORDER_VERIFICATION_FAILED', 'Work-order verification failed'), ('SAVED_RETURN_NOT_UNIQUE', 'Saved return not unique'), ('SAVED_RETURN_ROW_NOT_FOUND', 'Saved return row not found'), ('APPROVED_READY_TO_SUBMIT', 'Approved and ready to submit (submission disabled)'), ('SUBMITTING', 'Submitting (reserved)'), ('SUBMITTED', 'Submitted (reserved)'), ('WAITING_FOR_BIR_CONFIRMATION', 'Waiting for BIR confirmation (reserved)'), ('COMPLETED', 'Completed (reserved)'), ('FAILED_SYSTEM', 'System failure'), ('FAILED_BUSINESS', 'Business failure')], db_index=True, default='DRAFT', editable=False, max_length=40),
        ),
    ]
