# Generated by Django 5.2.17 on 2026-10-06 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0022_cancelled_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workorder',
            name='wo_m2_enabled_statuses',
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['CANCELLED', 'DRAFT', 'READY_TO_PREPARE', 'PROCESSING_PREPARATION', 'AWAITING_SUBMISSION_APPROVAL', 'PREPARATION_FAILED_PDF_NOT_FOUND', 'PREPARATION_FAILED_XML_NOT_FOUND', 'PROFILE_REVIEW_REQUIRED', 'FAILED_SYSTEM', 'FAILED_BUSINESS'])), name='wo_m2_enabled_statuses'),
        ),
    ]
